# Add all your templates here
require "templates/application"
require "templates/index"
require "templates/items"
require "templates/item"
require "templates/about"
require "templates/footer"
require "templates/header"
require "templates/news"
require "templates/contact"
require "templates/developer"
require "templates/item_types"
require "templates/input_enum_filter"
require "templates/input_filter_range_text"
